insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("MacBook Pro", "Computer", 3690000, "Apple", 30, "2.3GHz")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("MacBook Air", "Computer", 1720000, "Apple", 30, "3.5GHz")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("iPhoneSE", "SmartPhone", 550000, "Apple", 100, "4.7inch")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("iPhone11Pro", "SmartPhone", 1570000, "Apple", 95, "Super Retina XDR")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("AirPodsPro", "WirelessHeadphones", 329000, "Apple", 250, "NoiseCancling")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("Always9", "Computer", 2089000, "SAMSUNG", 40, "Core i7")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("NT550XCR-AD1A", "Computer", 449000, "SAMSUNG", 65, "Only Office")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("GalaxyS10+", "SmartPhone", 1889900, "SAMSUNG", 200, "128GB")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("GalaxyBuzzPlus", "WirelessHeadphones", 159000, "Apple", 250, "NoiseCancling")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("Gram17", "Computer", 1749000, "LG", 50, "860g")